name: "Docker build & push"

on:
  push:
    branches:
      - master
      - release_*
    paths:
      - deploy/**
      - label_studio/**
      - setup.py
      - .github/workflows/docker-build.yml
    tags: [ '*' ]

env:
  # increment it in case if you need to reset cache
  CACHE_NAME_PREFIX: v1
  NODE: '14'
  DOCKER_CLI_EXPERIMENTAL: enabled
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TAG: 'latest'

jobs:
  docker_build_and_push:
    name: "Docker build and push"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Override image tag on 'tag'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
      - name: Override image tag on 'tag'
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          echo "DOCKER_TAG=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "${{ env.NODE }}"


      - name: Upgrade npm
        run: npm install -g npm@7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2.1.7
        name: Configure npm cache
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('label_studio/frontend/package.json') }}-${{ hashFiles('label_studio/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-

      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2.1.7
        name: Configure pip cache
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-django-${{ hashFiles('deploy/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-django-

      - name: Install MW & LS
        run: |
          pip3 install -r deploy/requirements-mw.txt
          pip3 install -e .

      - name: Install LSF & set version.py
        run: ./deploy/prebuild.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        id: docker_build_and_push
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_eks:
    name: "Deploy image in EKS"
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release_test')
    needs: [docker_build_and_push]
    env:
      AWS_REGION: us-east-2
      CLUSTER_NAME: dev-cogniflow-cluster
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: kubeconfig dev
        id: kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }} --kubeconfig .kubeconfig
          echo "KUBE_CONFIG_DATA=$(cat .kubeconfig | base64)" >> $GITHUB_ENV
      - name: test kubeconfig
        run: echo $(echo QWxhZGRpbjpvcGVuIHNlc2FtZQ== | base64 --decode)
      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
          ECR_REGISTRY: ${{ env.REGISTRY }}
          ECR_REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.DOCKER_TAG }}
          KUBECTL_VERSION: "v1.21.0"
        with:
          args: set image deployment/$ECR_REPOSITORY $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
